server {
    listen 8099 default_server;
    allow 172.30.32.2;
    deny all;

    server_name _;
    root /www;
    index index.html;

    access_log /dev/stdout combined;
    error_log /dev/stdout info;

    location /api/ethio/ {
        proxy_pass http://127.0.0.1:8098/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
