export {
  clearWatchPaint,
  EMPTY_WATCH_STATUS,
  EthioWatch,
  getWatchStatus,
  sendWatchResult,
  setWatchArea,
  setWatchAtHome,
  startWatchPaint,
  syncWatchCatalog,
  syncWatchSnapshot,
  type WatchCatalog,
  type WatchCatalogArea,
  type WatchCatalogEntity,
  type WatchCommandPayload,
  type WatchCommandResult,
  type WatchModelDevice,
  type WatchModelEvent,
  type WatchNativeStatus,
  type WatchSnapshot,
} from "../../modules/ethio-watch/src/index";
